apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops-demo
data:
  # warning: base64 is NOT encryption - this is Phase 1 (K8s Secrets)
  DB_USER: YXBwX3VzZXI=
  DB_PASSWORD: Y2hhbmdlbWU=
  POSTGRES_USER: YXBwX3VzZXI=
  POSTGRES_PASSWORD: Y2hhbmdlbWU=
  POSTGRES_DB: ZGV2b3BzX2RlbW8=
