apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-demo
resources:
  # Namespace
  - namespace.yaml

  # Secrets and ConfigMaps
  - db-secret.yaml
  - api-configmap.yaml
  - frontend-configmap.yaml
  - init-sql-configmap.yaml

  #Databases
  - postgres-statefulset.yaml
  - postgres-service.yaml

  # API
  - api-deployment.yaml
  - api-service.yaml

  # Frontend
  - frontend-deployment.yaml
  - frontend-service.yaml
